name: Push Pipeline
on: [push, pull_request]
jobs:

  doc-spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y aspell aspell-en
      - run: bash .github/aspell.sh

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - run: pip install ruff
      - run: ruff --format=github --target-version=py37 .

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r ${{ github.workspace }}/test/requirements.txt
      - name: Running tests
        run: lit ${{ github.workspace }}/test --verbose

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r ${{ github.workspace }}\test\requirements.txt
      - name: Running tests
        shell: cmd
        run: lit ${{ github.workspace }}\test --verbose

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python3 -m pip install --upgrade build
      - run: python -m build
      - name: Upload .whl
        uses: actions/upload-artifact@v3
        with:
            name: bash-argparse
            path: dist/bash_argparse*.whl
            retention-days: 1

  test-package:
    runs-on: ubuntu-latest
    needs: [test-linux, test-windows, package] # doesn't really need test, but if the test don't pass, this one won't either
    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download a package
        uses: actions/download-artifact@v3
        with:
          name: bash-argparse
      - run: pip install bash_argparse*.whl
      - run: pip install -r ${{ github.workspace }}/test/requirements.txt
      - name: Running tests
        run: lit ${{ github.workspace }}/test --verbose -DUSE_INSTALLED=on
