name: Test 
on: [push, pull_request]
jobs:
  lint-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: py-actions/flake8@v2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r ${{ github.workspace }}/requirements.txt
      - name: Running legacy tests
        run: bash ${{ github.workspace }}/run_test.sh
      - name: Running tests
        run: lit ${{ github.workspace }}/test --verbose
